packages:
  - "BaseBackend"
  - "fe/nextjs-base"
  - "fe/nuxtjs-base"

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "core-js"
  - "core-js-pure"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
  - "vue-demi"
  - "yarn"
