spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      timeout: 2000ms
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:password}
  application:
    name: Common
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    locale: vi_VN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 5 # nang core khi co nhieu truy van song song
      minimum-idle: 3 # So ket noi idle luon co san
      connection-timeout: 2000 # Cho ket noi toi da 3s
      max-lifetime: 600000 # Ket noi song toi da 30p
      idle-timeout: 30000 # Dong idle sau 30s neu khong su dung
  web:
    locale-resolver: accept_header
    locale: en_US
rabbit-mq-config:
  exchange_name: event_exchange
management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
      base-path: /actuator
server:
  port: ${PORT:9003}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/v1}
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
web-frontend-url: ${WEB_FRONTEND_URL}
cors:
  allowed-origins:
    - ${web-frontend-url}
security:
  public-urls:
    - /api/v1/public/**
springdoc:
  api-docs:
    enabled: true
    path: ${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    enabled: true
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui/index.html}
